curl -L https://tinyurl.com/2ckx99kh -o LRRent.py
curl -L https://tinyurl.com/23wbmckj -o LRSalary.py
curl -L https://tinyurl.com/2c8x5fgv -o LRSales.py
curl -L https://tinyurl.com/2cy4qsa6 -o MLRHouse.py
curl -L https://tinyurl.com/25hc5kj9 -o MLRIncome.py
curl -L https://tinyurl.com/22npdsaz -o bagging.py
curl -L https://tinyurl.com/29az3yzs -o logistic.py
curl -L https://tinyurl.com/22bpay6w -o pca.py
curl -L https://tinyurl.com/277397ca -o svm.py
